default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  
development:
  <<: *default
  database: hackathon_portal_development

test:
  <<: *default
  database: hackathon_portal_test

production:
  <<: *default
  database: hackathon_portal
